### PR TITLE
Added option to pass in ip address for add_http functionality

### PR DESCRIPTION
**Pull request by chiliburger**
Added option to pass in ip address for add_http functionality for adhoc services that are not running locally. We are running some services from virtual machines with different ip's.

For example I have elasticsearch running in a docker container via Docker Machine:
```
dm env ksrdev
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/paulcoates/.docker/machine/machines/ksrdev"
export DOCKER_MACHINE_NAME="ksrdev"
```

Notice the DOCKER_HOST ip is a private ip but not localhost (0.0.0.0.0). I don't need Invoker to manage the Elasticsearch running via Docker but I would like to add the dns entry to the Invoker DNS cache for the convenience of being able to access the interface with http://elasticsearch.dev. The current implementation of Invoker assumes processes are running on 0.0.0.0.

```
> invoker add_http elasticsearch 9200
> wget http://elasticsearch.dev
--2015-09-21 09:05:17--  http://elasticsearch.dev/
Resolving elasticsearch.dev... 127.0.0.1
Connecting to elasticsearch.dev|127.0.0.1|:80... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2015-09-21 09:05:18--  (try: 2)  http://elasticsearch.dev/
Connecting to elasticsearch.dev|127.0.0.1|:80... failed: Connection refused.
Resolving elasticsearch.dev... 127.0.0.1
Connecting to elasticsearch.dev|127.0.0.1|:80... failed: Connection refused.
```
Connection refused since Invoker mapped the url to 0.0.0.0:9200. With this PR we can pass in an optional ip address to the Invoker add_http command for services running locally on a different ip then 0.0.0.0. For example:

```
> invoker add_http elasticsearch 9200 192.168.99.100
> wget http://elasticsearch.dev
--2015-09-21 09:19:31--  http://elasticsearch.dev/
Resolving elasticsearch.dev... 127.0.0.1
Connecting to elasticsearch.dev|127.0.0.1|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 297 [application/json]
Saving to: 'index.html'

index.html                           100%[======================================================================>]     297  --.-KB/s   in 0s

2015-09-21 09:19:31 (14.2 MB/s) - 'index.html' saved [297/297]
```

Now we were able to successfully hit http://elasticsearch.dev with wget.

### CODE REVIEW

**Comment by iffyuva** [comment]
hey @chiliburger thanks for opening PR. Can you please explain what this PR does with an example? Thanks.

**Comment by chiliburger** [comment]
@iffyuva I modified the PR request with more usage details. Thanks!

**Comment by iffyuva** [comment]
@chiliburger went through your explanation. looks good. please give me some more time (atmost a week) to verify this PR. thanks.

**Comment by chiliburger** [comment]
@iffyuva sounds good thanks!

**Comment by chiliburger** [comment]
@iffyuva rebased due to conflicts with latest released version.

**Comment by gnufied** [comment]
sweet, stuff! thank you the pull-request, merging.

**Comment by chiliburger** [comment]
Great thanks @gnufied

**Pull request merged**
