### PR TITLE
Default process sleep_duration to 0

### LINKED ISSUE #226: Why isn't it possible to set sleep_duration to 0?
I don't get why I have to wait 1 second before invoker starts any of my processes. I can't even set the value to 0 manually because [it's overridden](https://github.com/code-mancers/invoker/blob/v1.5.6/lib/invoker/parsers/config.rb#L136).

### PR DESCRIPTION
**Pull request by swrobel**
I see no ill effects of this, so I don't see why everyone should be waiting 1 second between processes starting by default. It's wasting precious time. Fixes #226

### CODE REVIEW

**Comment by swrobel** [comment]
@gnufied do you still want to review these or should I just start merging? I'm interested in your review here, especially because you originally made the change to set sleep_duration to a minimum of 1

**Comment by swrobel** [comment]
@gnufied I hate to bug you at all as I imagine you're quite busy, but I'd love to get your thoughts on this PR in particular. I'm happy to go ahead and merge all of them to save you the trouble of resolving conflicts.

**Comment by gnufied** [comment]
can you fix the conflict? I remember putting 1s sleep because spawning processes without sleep was causing some issues.

**Comment by swrobel** [comment]
Conflict fixed. I've been using this change for a while w/ 4 processes & have had no issues on macOS.

**Pull request merged**
