### PR TITLE
Implements auto-detection of Procfile or .ini config file

### LINKED ISSUE #65: Auto detect default configuration file
Thanks for building this. I've been looking for a better alternative to Foreman.

Similar to how `foreman start` works, it would be nice if running `invoker start` would automatically detect either a `invoker.ini` or `Procfile`.

If this sounds like a reasonable feature, I can attempt a pull request.

### PR DESCRIPTION
**Pull request by dwbutler**
Fixes #65. Usage:

```invoker start```

Automatically detects a config file in the following precedence: `Procfile`, `invoker.ini`, `project.ini`, `*.ini`.

### CODE REVIEW

**Comment by mtylty** [comment]
is this gonna be merged?

**Comment by lorenjohnson** [comment]
:+1:

**Comment by lorenjohnson** [comment]
:+1:

**Comment by nisanth074** [comment]
When we are autodetecting config file, I prefer we glob only `invoker.ini, Procfile, Procfile.*` (also in that order). `project.ini` is too specific to be autodetected, `*.ini` is too generic.

We can have a bundler like config system where someone can say
```
invoker config config_file project.ini
```
In subsequent calls to `invoker start`, `project.ini` will be used as the config file

@iffyuva Thoughts?

**Comment by nisanth074** [comment]
For a start, we can autodetect, `invoker.ini`, `Procfile` (in that order). Will merge this some time this week.

**Comment by nisanth074** [comment]
For a start, we can autodetect, `invoker.ini`, `Procfile` (in that order). Will merge this some time this week.

**Comment by nisanth074** [comment]
Merged this in #150

@dwbutler Thank you for contributing to invoker :)

**Comment by dwbutler** [comment]
:+1:

**Pull request merged**
