### PR TITLE
Process ordering

### PR DESCRIPTION
**Pull request by gnufied**
Implement support for adding index to processes such that they can be started in specific order.

### CODE REVIEW

**Comment by gnufied** [comment]
@iffyuva can you have a look?

**Comment by iffyuva** [comment]
@gnufied i looked at this PR today morning, and PR looks good. only concern is backward compatibility. let me try out this branch for couple of projects, and i will let you know. thanks.

**Comment by gnufied** [comment]
I think it should be 100% backward compatible, the only change that users not using this feature will see is - 1s delay between starting their processes. I added that because, sometimes when processes are dependent - it is a good idea to introduce some delay between starting them. But we can probably drop it too.

**Comment by nisanth074** [comment]
Just curious. Can two processes have the same index?
```
[postgres]
directory = /Users/nisanth/code/SupportBee-Rails
command = /Users/nisanth/.pgvm/environments/current/bin/postgres -D /usr/local/var/postgres
index = 1

[redis]
directory = /Users/nisanth/builds/redis-2.4.2/src
command = ./redis-server /usr/local/etc/redis.conf
index = 1

[rails]
directory = /Users/nisanth/code/SupportBee-Rails
; Depends on redis and postgres
command = bundle exec rails s
index = 2
```

**Comment by gnufied** [comment]
Yeah they can, in which case they would be ordered by order in which they were parsed.  In fact if a process has to no index, currently it is assigned 0 index.

**Comment by gnufied** [comment]
It may be worth assigning higher index for processes without explicit index, rather than 0. @nisanth074  what you think?

**Comment by nisanth074** [comment]
@gnufied If I add a process which doesn't depend on anything else
```
[postgres]
directory = /Users/nisanth/code/SupportBee-Rails
command = /Users/nisanth/.pgvm/environments/current/bin/postgres -D /usr/local/var/postgres
index = 1

[redis]
directory = /Users/nisanth/builds/redis-2.4.2/src
command = ./redis-server /usr/local/etc/redis.conf
index = 1

[rails]
directory = /Users/nisanth/code/SupportBee-Rails
; Depends on redis and postgres
command = bundle exec rails s
index = 2

[faye]
directory = /Users/nisanth/code/SupportBee-Rails
; We used to use faye for push events
; I'd intuitively expect faye to be started immediately
command = bundle exec faye
```
I'd intuitively expect the process to be started immediately. Hence I feel defaulting to 0 index for processes without explicit index is fine.

**Comment by iffyuva** [comment]
couple of things to discuss:

- index can be implicit, ie order in which processes appear in ini file is the order in which we can assign an index, and start processes
- should `invoker list` show index of process?

**Pull request merged**
