### PR TITLE
Tjlivesey master

### PR DESCRIPTION
**Pull request by gnufied**

### CODE REVIEW

**Comment by localredhead** [comment]
I tried pulling down master and building/installing the gem locally - though I was not very successful in adding things to my Procfile that contain a period in the service name.  i.e. www.app.dev or www.app 

I'll wait for the gem update.

**Comment by gnufied** [comment]
I think thats because `Procfile` specs do not allow `.` in process labels, https://github.com/ddollar/foreman/blob/master/lib/foreman/procfile.rb

So, `foo.bar: bundle exec rails s` is a not parsed correctly. I suppose, we can extend the `Procfile` syntax to support `.` in the name but I am hesitant to deviate from official specs.

**Comment by localredhead** [comment]
That is a shame but IMHO its best not to stray from the the procfile spec if its a format that will be supported.

What if invoker used symlinks for HTTP services like POW,  and then procfiles and INI's for everything else?

__I apologize__ if this has already been asked before. I cringe at making the suggestion, but I have a few reasons why I ask:

1.  It would allow Procfiles and INI's to have _parallel functionality_.  I think this is really important.
2.  The symlinks are very flexible in terms of naming
3.  It could, perhaps, be easier to support things like www.app and www.app.dev and such but just using symlinks.
4.  It seperates concerns.  For example ```~/.invoker/http/``` could contain all symlinks mimmicking POW's usage of symlinks, and the Procfiles and INI's can focus one what they do best - manage the services. 
5.  The ```invoker add_http``` command could actually __persist__ the value as a symlink.

Again, I am sorry if this suggestion is offensive to the directions of decisions that have been made previously.  I feel like POW is a bit more usable because of its ability to support subdomains with a simple symlink and I think if Invoker had the same paradigm it would excel.

Thoughts?

**Comment by gnufied** [comment]
Well, Pow can only manage http only programs whereas Invoker is a generic process supervisor which can manage pretty much anything. 

I am not keen on supporting symlink feature for Invoker. I spoke with Foreman author though and apparently not allowing `.` in process labels was a minor oversight. There is no particular reason Procfiles can't support that. So I am looking forward to update Procfile specs so as `.` is allowed in Procfile names, so as Invoker can support it too.

**Comment by localredhead** [comment]
Even better :+1:

**Pull request merged**
